= Enhancing Boot Application with Metrics

== Set up the Actuator

Spring Boot includes a number of additional features to help you monitor and manage your application when it’s pushed to production. These features are added by adding _spring-boot-starter-actuator_ to the classpath.  During our initial project setup with *start.spring.io* we've already included that.

. Verify the Spring Boot Actuator dependency the following file: */cloud-native-spring/pom.xml*.  You should see the following dependency in the list:
+
[source, xml]
---------------------------------------------------------------------
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
---------------------------------------------------------------------

. Run the updated application
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean spring-boot:run
---------------------------------------------------------------------
+
Try out the following endpoints. The output is omitted here because it can be quite large:
+
http://localhost:8080/health
+
Displays Application and Datasource health information.  This can be customized based on application functionality, which we'll do later.
+
http://localhost:8080/beans
+
Dumps all of the beans in the Spring context.
+
http://localhost:8080/autoconfig
+
Dumps all of the auto-configuration performed as part of application bootstrapping.
+
http://localhost:8080/configprops
+
Displays a collated list of all @ConfigurationProperties.
+
http://localhost:8080/env
+
Dumps the application’s shell environment as well as all Java system properties.
+
http://localhost:8080/mappings
+
Dumps all URI request mappings and the controller methods to which they are mapped.
+
http://localhost:8080/dump
+
Performs a thread dump.
+
http://localhost:8080/trace
+
Displays trace information (by default the last few HTTP requests).

. Stop the cloud-native-spring application.


== Health Indicators

Spring Boot provides an endpoint http://localhost:8080/health that exposes various health indicators that describe the health of the given application.

Normally, when Spring Security is not enabled, the /health endpoint will only expose an UP or DOWN value.

[source,json]
---------------------------------------------------------------------
{
  "status": "UP"
}
---------------------------------------------------------------------

. To simplify working with the endpoint for this lab, we will turn off its sensitivity. Add the following to */cloud-native-spring/src/main/resources/application.yml*:
+
[source, yaml]
---------------------------------------------------------------------
endpoints:
  health:
    sensitive: false
---------------------------------------------------------------------

. Build and run the cloud-native-spring application:
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean spring-boot:run
---------------------------------------------------------------------

. Browse to http://localhost:8080/health. Out of the box is a _DiskSpaceHealthIndicator_ that monitors health in terms of available disk space. Would your Ops team like to know if the app is close to running out of disk space? DiskSpaceHealthIndicator can be customized via _DiskSpaceHealthIndicatorProperties_. For instance, setting a different threshold for when to report the status as DOWN.
+
[source,json]
---------------------------------------------------------------------
{
  "status": "UP",
  "diskSpace": {
      "status": "UP",
      "free": 42345678945,
      "threshold": 12345678
  }
}
---------------------------------------------------------------------

. Stop the cloud-native-spring application.

. Create the class _io.pivotal.FlappingHealthIndicator_ (/cloud-native-spring/src/main/java/io/pivotal/FlappingHealthIndicator.java) and into it paste the following code:
+
[source,java]
---------------------------------------------------------------------
package io.pivotal;

import java.util.Random;

import org.springframework.boot.actuate.health.Health;
import org.springframework.boot.actuate.health.HealthIndicator;
import org.springframework.stereotype.Component;

@Component
public class FlappingHealthIndicator implements HealthIndicator {

    private Random random = new Random(System.currentTimeMillis());

    @Override
    public Health health() {
        int result = random.nextInt(100);
        if (result < 50) {
            return Health.down().withDetail("flapper", "failure").withDetail("random", result).build();
        } else {
            return Health.up().withDetail("flapper", "ok").withDetail("random", result).build();
        }
    }
}
---------------------------------------------------------------------
+
This demo health indicator will randomize the health check.

. Build and run the _cloud-native-spring_ application:
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean spring-boot:run
---------------------------------------------------------------------

. Browse to http://localhost:8080/health and verify that the output is similar to the following (and changes randomly!).
+
[source,json]
---------------------------------------------------------------------
{
  "status": "UP",
  "flapping": {
      "status": "UP",
      "flapper": "ok",
      "random": 42
  },
  "diskSpace": {
      "status": "UP",
      "free": 42345678945,
      "threshold": 12345678
  }
}
---------------------------------------------------------------------

== Metrics

Spring Boot provides an endpoint http://localhost:8080/metrics that exposes several automatically collected metrics for your application. It also allows for the creation of custom metrics.

. Browse to http://localhost:8080/metrics. Review the metrics exposed.
+
[source,json]
---------------------------------------------------------------------
{
"mem": 418830,
"mem.free": 239376,
"processors": 8,
"instance.uptime": 59563,
"uptime": 69462,
"systemload.average": 1.5703125,
"heap.committed": 341504,
"heap.init": 262144,
"heap.used": 102127,
"heap": 3728384,
"nonheap.committed": 79696,
"nonheap.init": 2496,
"nonheap.used": 77326,
"nonheap": 0,
"threads.peak": 14,
"threads.daemon": 11,
"threads.totalStarted": 17,
"threads": 13,
"classes": 9825,
"classes.loaded": 9825,
"classes.unloaded": 0,
"gc.ps_scavenge.count": 9,
"gc.ps_scavenge.time": 80,
"gc.ps_marksweep.count": 2,
"gc.ps_marksweep.time": 157,
"httpsessions.max": -1,
"httpsessions.active": 0,
"gauge.response.metrics": 75,
"gauge.response.star-star.favicon.ico": 9,
"counter.status.200.star-star.favicon.ico": 1,
"counter.status.200.metrics": 1
}
---------------------------------------------------------------------

. Stop the cloud-native-spring application.

== Deploy _cloud-native-spring_ to Pivotal Cloud Foundry
. Build the application
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean package
---------------------------------------------------------------------

. Push application into Cloud Foundry
+
$ cf push -f manifest.yml

. Find the URL created for your app in the health status report. Browse to your app.

*Congratulations!* You’ve just learned how to add health and metrics to any Spring Boot application.
